# Archivo de configuración específico para el entorno de producción.
# Contiene configuraciones para la base de datos H2 en memoria, opciones de JPA y rutas de archivos CSV.

spring:
  datasource:
    url: jdbc:h2:mem:comunidadesdb;DB_CLOSE_ON_EXIT=FALSE  # URL de la base de datos en memoria H2.
    username: sa  # Nombre de usuario de la base de datos H2.
    password:  # Contraseña de la base de datos (vacía en producción).
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # Dialecto de H2 para JPA.
    show-sql: false  # Oculta las consultas SQL en la consola en producción.
    hibernate:
      ddl-auto: update  # Actualiza automáticamente el esquema de la base de datos.
  h2:
    console:
      enabled: false  # Deshabilita la consola H2 en producción para mayor seguridad.

# Configuración de rutas de archivos CSV para inicializar datos de comunidades y provincias.
csv:
  comunidades:
    path: classpath:COMUNIDAD_AUTONOMA.csv  # Ruta del archivo CSV de comunidades autónomas.
  provincias:
    path: classpath:PROVINCIA.csv  # Ruta del archivo CSV de provincias.

# Configuración del servidor para producción.
server:
  port: 8080  # Puerto estándar en el que se ejecutará la aplicación en producción.
